package org.kgen.reflect

import org.kgen.binary.ObjectFile
import org.kgen.binary.SectionKind
import org.kgen.binary.SymbolKind
import java.lang.foreign.*
import java.lang.foreign.ValueLayout.*
import java.lang.invoke.MethodHandle

/**
 * Load machine code into executable memory and call it.
 *
 * ```java
 * // From an ObjectFile (generated by X86CodeGenerator)
 * var module = NativeCode.load(objectFile);
 * long result = module.call("add", 3, 4);  // 7
 * module.close();
 *
 * // From raw bytes
 * var module = NativeCode.loadBytes(machineCode, Map.of("add", 0L));
 * long result = module.call("add", 3, 4);
 * module.close();
 * ```
 */
class NativeCode private constructor(
    private val mem: NativeMemory,
    private val symbolOffsets: Map<String, Long>,
) : AutoCloseable {

    /** Base address where the code is loaded. */
    val baseAddress: Long get() = mem.address

    /** All symbol names in the loaded code. */
    fun symbols(): Set<String> = symbolOffsets.keys

    /** Get the absolute address of a symbol, or null if not found. */
    fun symbolAddress(name: String): Long? {
        val offset = symbolOffsets[name] ?: return null
        return mem.address + offset
    }

    /** Read the raw bytes of the loaded code. */
    fun codeBytes(): ByteArray = mem.read(0, mem.size.toInt())

    /** Read [length] bytes starting at [offset] from the code base. */
    fun readCode(offset: Long, length: Int): ByteArray = mem.read(offset, length)

    /** Overwrite code at [offset]. Use with caution. */
    fun patchCode(offset: Long, data: ByteArray) = mem.write(offset, data)

    /**
     * Call a function by name with long arguments, returning long.
     * This is the most common case for native code (pointers and integers are all longs).
     */
    fun call(name: String, vararg args: Long): Long {
        val addr = symbolAddress(name)
            ?: throw IllegalArgumentException("Symbol not found: $name")
        return callAt(addr, *args)
    }

    /** Call a function at an absolute address with long arguments, returning long. */
    fun callAt(address: Long, vararg args: Long): Long {
        val desc = makeDescriptor(JAVA_LONG, args.size)
        val handle = linker.downcallHandle(MemorySegment.ofAddress(address), desc)
        return invokeHandle(handle, args) as Long
    }

    /** Call a function by name, returning int. */
    fun callInt(name: String, vararg args: Long): Int {
        val addr = symbolAddress(name)
            ?: throw IllegalArgumentException("Symbol not found: $name")
        val desc = makeDescriptor(JAVA_INT, args.size)
        val handle = linker.downcallHandle(MemorySegment.ofAddress(addr), desc)
        return invokeHandle(handle, args) as Int
    }

    /** Call a function by name, returning void. */
    fun callVoid(name: String, vararg args: Long) {
        val addr = symbolAddress(name)
            ?: throw IllegalArgumentException("Symbol not found: $name")
        val desc = FunctionDescriptor.ofVoid(*Array(args.size) { JAVA_LONG })
        val handle = linker.downcallHandle(MemorySegment.ofAddress(addr), desc)
        invokeHandle(handle, args)
    }

    override fun close() {
        mem.close()
    }

    companion object {
        private val linker = Linker.nativeLinker()

        /**
         * Load an [ObjectFile] (from X86CodeGenerator, etc.) into executable memory.
         * Extracts the .text section and symbol table.
         */
        @JvmStatic
        fun load(obj: ObjectFile): NativeCode {
            val textSection = obj.sections.firstOrNull { it.kind == SectionKind.TEXT }
                ?: throw IllegalArgumentException("No TEXT section found")
            val code = textSection.data
            if (code.isEmpty()) throw IllegalArgumentException("TEXT section is empty")

            val symbolMap = mutableMapOf<String, Long>()
            for (sym in obj.symbols) {
                if (sym.kind != SymbolKind.UNDEFINED) {
                    symbolMap[sym.name] = sym.value
                }
            }

            return loadBytes(code, symbolMap)
        }

        /**
         * Load raw machine code bytes into executable memory.
         * [symbols] maps symbol names to offsets within the code.
         */
        @JvmStatic
        fun loadBytes(code: ByteArray, symbols: Map<String, Long> = emptyMap()): NativeCode {
            val mem = NativeMemory.allocateExecutable(code.size.toLong())
            mem.write(0, code)
            return NativeCode(mem, symbols)
        }

        private fun makeDescriptor(returnType: MemoryLayout, paramCount: Int): FunctionDescriptor {
            return FunctionDescriptor.of(returnType, *Array(paramCount) { JAVA_LONG })
        }

        private fun invokeHandle(handle: MethodHandle, args: LongArray): Any? = when (args.size) {
            0 -> handle.invoke()
            1 -> handle.invoke(args[0])
            2 -> handle.invoke(args[0], args[1])
            3 -> handle.invoke(args[0], args[1], args[2])
            4 -> handle.invoke(args[0], args[1], args[2], args[3])
            5 -> handle.invoke(args[0], args[1], args[2], args[3], args[4])
            6 -> handle.invoke(args[0], args[1], args[2], args[3], args[4], args[5])
            else -> handle.invokeWithArguments(*args.map { it as Any }.toTypedArray())
        }
    }
}
