package org.kgen.reflect

import org.kgen.binary.*
import java.lang.foreign.*
import java.lang.foreign.ValueLayout.*
import java.lang.invoke.MethodHandle

/**
 * Load machine code into executable memory and call it.
 *
 * ```java
 * // From an ObjectFile (generated by X86CodeGenerator)
 * var module = NativeCode.load(objectFile);
 * long result = module.call("add", 3, 4);  // 7
 * module.close();
 *
 * // From raw bytes
 * var module = NativeCode.loadBytes(machineCode, Map.of("add", 0L));
 * long result = module.call("add", 3, 4);
 * module.close();
 * ```
 */
class NativeCode private constructor(
    private val mem: NativeMemory,
    private val symbolOffsets: Map<String, Long>,
) : AutoCloseable {

    /** Base address where the code is loaded. */
    val baseAddress: Long get() = mem.address

    /** All symbol names in the loaded code. */
    fun symbols(): Set<String> = symbolOffsets.keys

    /** Get the absolute address of a symbol, or null if not found. */
    fun symbolAddress(name: String): Long? {
        val offset = symbolOffsets[name] ?: return null
        return mem.address + offset
    }

    /** Read the raw bytes of the loaded code. */
    fun codeBytes(): ByteArray = mem.read(0, mem.size.toInt())

    /** Read [length] bytes starting at [offset] from the code base. */
    fun readCode(offset: Long, length: Int): ByteArray = mem.read(offset, length)

    /** Overwrite code at [offset]. Use with caution. */
    fun patchCode(offset: Long, data: ByteArray) = mem.write(offset, data)

    /**
     * Call a function by name with long arguments, returning long.
     * This is the most common case for native code (pointers and integers are all longs).
     */
    fun call(name: String, vararg args: Long): Long {
        val addr = symbolAddress(name)
            ?: throw IllegalArgumentException("Symbol not found: $name")
        return callAt(addr, *args)
    }

    /** Call a function at an absolute address with long arguments, returning long. */
    fun callAt(address: Long, vararg args: Long): Long {
        val desc = makeDescriptor(JAVA_LONG, args.size)
        val handle = linker.downcallHandle(MemorySegment.ofAddress(address), desc)
        return invokeHandle(handle, args) as Long
    }

    /** Call a function by name, returning int. */
    fun callInt(name: String, vararg args: Long): Int {
        val addr = symbolAddress(name)
            ?: throw IllegalArgumentException("Symbol not found: $name")
        val desc = makeDescriptor(JAVA_INT, args.size)
        val handle = linker.downcallHandle(MemorySegment.ofAddress(addr), desc)
        return invokeHandle(handle, args) as Int
    }

    /** Call a function by name, returning float. */
    fun callFloat(name: String, vararg args: Long): Float {
        val addr = symbolAddress(name)
            ?: throw IllegalArgumentException("Symbol not found: $name")
        val desc = makeDescriptor(JAVA_FLOAT, args.size)
        val handle = linker.downcallHandle(MemorySegment.ofAddress(addr), desc)
        return invokeHandle(handle, args) as Float
    }

    /** Call a function by name, returning double. */
    fun callDouble(name: String, vararg args: Long): Double {
        val addr = symbolAddress(name)
            ?: throw IllegalArgumentException("Symbol not found: $name")
        val desc = makeDescriptor(JAVA_DOUBLE, args.size)
        val handle = linker.downcallHandle(MemorySegment.ofAddress(addr), desc)
        return invokeHandle(handle, args) as Double
    }

    /** Call a function by name, returning void. */
    fun callVoid(name: String, vararg args: Long) {
        val addr = symbolAddress(name)
            ?: throw IllegalArgumentException("Symbol not found: $name")
        val desc = FunctionDescriptor.ofVoid(*Array(args.size) { JAVA_LONG })
        val handle = linker.downcallHandle(MemorySegment.ofAddress(addr), desc)
        invokeHandle(handle, args)
    }

    override fun close() {
        mem.close()
    }

    companion object {
        private val linker = Linker.nativeLinker()

        /**
         * Load an [ObjectFile] (from X86CodeGenerator, etc.) into executable memory.
         * Extracts the .text and .rodata sections, resolves internal relocations,
         * and builds a symbol table for calling functions by name.
         */
        @JvmStatic
        fun load(obj: ObjectFile): NativeCode {
            val textSection = obj.sections.firstOrNull { it.kind == SectionKind.TEXT }
                ?: throw IllegalArgumentException("No TEXT section found")
            val code = textSection.data
            if (code.isEmpty()) throw IllegalArgumentException("TEXT section is empty")

            val rodataSection = obj.sections.firstOrNull { it.kind == SectionKind.RODATA }
            val rodataSize = rodataSection?.data?.size?.toLong() ?: 0L
            val totalSize = code.size.toLong() + rodataSize

            val mem = NativeMemory.allocateExecutable(totalSize)
            mem.write(0, code)

            val rodataOffset = code.size.toLong()
            if (rodataSection != null && rodataSection.data.isNotEmpty()) {
                mem.write(rodataOffset, rodataSection.data)
            }

            // Build symbol address map (absolute addresses)
            val symbolAddrs = mutableMapOf<String, Long>()
            val symbolOffsets = mutableMapOf<String, Long>()
            for (sym in obj.symbols) {
                if (sym.kind == SymbolKind.UNDEFINED) continue
                val offset = when (sym.section) {
                    ".rodata" -> rodataOffset + sym.value
                    else -> sym.value
                }
                symbolAddrs[sym.name] = mem.address + offset
                symbolOffsets[sym.name] = offset
            }

            // Apply relocations
            applyRelocations(obj.relocations, mem, symbolAddrs)
            for (section in obj.sections) {
                if (section.relocations.isNotEmpty()) {
                    applyRelocations(section.relocations, mem, symbolAddrs)
                }
            }

            return NativeCode(mem, symbolOffsets)
        }

        private fun applyRelocations(
            relocations: List<Relocation>,
            mem: NativeMemory,
            symbols: Map<String, Long>,
        ) {
            for (rel in relocations) {
                val targetAddr = symbols[rel.symbol] ?: continue
                val patchAddr = mem.address + rel.offset

                when (rel.type) {
                    RelocationType.X86_64.PC32, RelocationType.X86_64.PLT32 -> {
                        val value = (targetAddr + rel.addend - patchAddr).toInt()
                        mem.writeInt(rel.offset, value)
                    }
                    RelocationType.X86_64.R_32, RelocationType.X86_64.R_32S -> {
                        val value = (targetAddr + rel.addend).toInt()
                        mem.writeInt(rel.offset, value)
                    }
                    RelocationType.X86_64.R_64 -> {
                        val value = targetAddr + rel.addend
                        mem.writeLong(rel.offset, value)
                    }
                    RelocationType.AArch64.CALL26, RelocationType.AArch64.JUMP26 -> {
                        val delta = targetAddr + rel.addend - patchAddr
                        val existing = mem.readInt(rel.offset)
                        val imm26 = ((delta shr 2) and 0x03FFFFFFL).toInt()
                        mem.writeInt(rel.offset, (existing and 0xFC000000.toInt()) or imm26)
                    }
                    RelocationType.AArch64.ADR_PREL_PG_HI21 -> {
                        val target = targetAddr + rel.addend
                        val page = (target and 0xFFFFF000L) - (patchAddr and 0xFFFFF000L)
                        val immHi = ((page shr 12) and 0x1FFFFFL).toInt()
                        val immLo = (immHi and 0x3) shl 29
                        val immHiField = ((immHi shr 2) and 0x7FFFF) shl 5
                        val existing = mem.readInt(rel.offset)
                        mem.writeInt(rel.offset, (existing and 0x9F00001F.toInt()) or immLo or immHiField)
                    }
                    RelocationType.AArch64.ADD_ABS_LO12_NC,
                    RelocationType.AArch64.LDST8_ABS_LO12_NC -> {
                        val imm12 = ((targetAddr + rel.addend) and 0xFFFL).toInt()
                        val existing = mem.readInt(rel.offset)
                        mem.writeInt(rel.offset, (existing and 0xFFC003FF.toInt()) or (imm12 shl 10))
                    }
                    RelocationType.AArch64.LDST32_ABS_LO12_NC -> {
                        val imm12 = (((targetAddr + rel.addend) and 0xFFFL).toInt() shr 2) and 0xFFF
                        val existing = mem.readInt(rel.offset)
                        mem.writeInt(rel.offset, (existing and 0xFFC003FF.toInt()) or (imm12 shl 10))
                    }
                    RelocationType.AArch64.LDST64_ABS_LO12_NC -> {
                        val imm12 = (((targetAddr + rel.addend) and 0xFFFL).toInt() shr 3) and 0xFFF
                        val existing = mem.readInt(rel.offset)
                        mem.writeInt(rel.offset, (existing and 0xFFC003FF.toInt()) or (imm12 shl 10))
                    }
                    RelocationType.AArch64.ABS64 -> {
                        mem.writeLong(rel.offset, targetAddr + rel.addend)
                    }
                    RelocationType.AArch64.PREL32 -> {
                        val value = (targetAddr + rel.addend - patchAddr).toInt()
                        mem.writeInt(rel.offset, value)
                    }
                    else -> {} // Skip unsupported relocation types
                }
            }
        }

        /**
         * Load raw machine code bytes into executable memory.
         * [symbols] maps symbol names to offsets within the code.
         */
        @JvmStatic
        fun loadBytes(code: ByteArray, symbols: Map<String, Long> = emptyMap()): NativeCode {
            val mem = NativeMemory.allocateExecutable(code.size.toLong())
            mem.write(0, code)
            return NativeCode(mem, symbols)
        }

        private fun makeDescriptor(returnType: MemoryLayout, paramCount: Int): FunctionDescriptor {
            return FunctionDescriptor.of(returnType, *Array(paramCount) { JAVA_LONG })
        }

        private fun invokeHandle(handle: MethodHandle, args: LongArray): Any? = when (args.size) {
            0 -> handle.invoke()
            1 -> handle.invoke(args[0])
            2 -> handle.invoke(args[0], args[1])
            3 -> handle.invoke(args[0], args[1], args[2])
            4 -> handle.invoke(args[0], args[1], args[2], args[3])
            5 -> handle.invoke(args[0], args[1], args[2], args[3], args[4])
            6 -> handle.invoke(args[0], args[1], args[2], args[3], args[4], args[5])
            else -> handle.invokeWithArguments(*args.map { it as Any }.toTypedArray())
        }
    }
}
