package org.kgen.jit.runtime

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.condition.EnabledOnOs
import org.junit.jupiter.api.condition.OS

@EnabledOnOs(OS.LINUX, OS.WINDOWS)
class StubGeneratorTest {

    @Test
    fun trampolineHasNonZeroAddress() {
        val gen = X86StubGenerator()
        val stub = gen.generateTrampoline(0xDEADBEEFL)
        assertTrue(stub.address() != 0L)
        assertTrue(stub.size() > 0)
        stub.close()
    }

    @Test
    fun trampolineStartsWithMovabs() {
        val gen = X86StubGenerator()
        val stub = gen.generateTrampoline(0x12345678L)
        val mem = org.kgen.reflect.NativeMemory.viewAt(stub.address(), stub.size())
        assertEquals(0x49.toByte(), mem.readByte(0))  // REX.WB
        assertEquals(0xBB.toByte(), mem.readByte(1))  // movabs r11
        mem.close()
        stub.close()
    }

    @Test
    fun trampolineEncodesAddress() {
        val gen = X86StubGenerator()
        val target = 0x00007FFF12345678L
        val stub = gen.generateTrampoline(target)
        val mem = org.kgen.reflect.NativeMemory.viewAt(stub.address(), stub.size())
        val encoded = mem.readLong(2) // address starts at offset 2
        assertEquals(target, encoded)
        mem.close()
        stub.close()
    }

    @Test
    fun trampolineEndsWithJmpR11() {
        val gen = X86StubGenerator()
        val stub = gen.generateTrampoline(0L)
        val mem = org.kgen.reflect.NativeMemory.viewAt(stub.address(), stub.size())
        assertEquals(0x41.toByte(), mem.readByte(10)) // REX.B
        assertEquals(0xFF.toByte(), mem.readByte(11)) // jmp
        assertEquals(0xE3.toByte(), mem.readByte(12)) // r11
        mem.close()
        stub.close()
    }

    @Test
    fun callStubHasNonZeroAddress() {
        val gen = X86StubGenerator()
        val stub = gen.generateCallStub(0x1000, 2)
        assertTrue(stub.address() != 0L)
        stub.close()
    }

    @Test
    fun callStubStartsWithPushRbp() {
        val gen = X86StubGenerator()
        val stub = gen.generateCallStub(0x1000, 0)
        val mem = org.kgen.reflect.NativeMemory.viewAt(stub.address(), stub.size())
        assertEquals(0x55.toByte(), mem.readByte(0)) // push rbp
        mem.close()
        stub.close()
    }

    @Test
    fun callStubEndsWithRet() {
        val gen = X86StubGenerator()
        val stub = gen.generateCallStub(0x1000, 0)
        // Read the generated bytes to find ret
        val mem = org.kgen.reflect.NativeMemory.viewAt(stub.address(), stub.size())
        // push rbp (1) + mov rbp,rsp (3) + sub rsp,32 (4) + movabs r11 (10) + call r11 (3) + add rsp,32 (4) + pop rbp (1) + ret (1) = 27 bytes
        assertEquals(0xC3.toByte(), mem.readByte(26)) // ret
        mem.close()
        stub.close()
    }

    @Test
    fun savingCallStubPreservesCalleeSaved() {
        val gen = X86StubGenerator()
        val stub = gen.generateSavingCallStub(0x1000)
        assertTrue(stub.address() != 0L)
        assertTrue(stub.size() >= 40) // non-trivial stub
        stub.close()
    }

    @Test
    fun safepointPollStubGenerated() {
        val gen = X86StubGenerator()
        val stub = gen.generateSafepointPoll(0x1000, 0x2000)
        assertTrue(stub.address() != 0L)
        stub.close()
    }

    @Test
    fun stubNameIsSet() {
        val gen = X86StubGenerator()
        val stub = gen.generateTrampoline(0)
        assertEquals("trampoline", stub.name)
        stub.close()

        val callStub = gen.generateCallStub(0, 3)
        assertEquals("call_stub_3", callStub.name)
        callStub.close()
    }

    @Test
    fun multipleStubsIndependent() {
        val gen = X86StubGenerator()
        val s1 = gen.generateTrampoline(0x1000)
        val s2 = gen.generateTrampoline(0x2000)
        assertNotEquals(s1.address(), s2.address())
        s1.close()
        s2.close()
    }

    @Test
    fun trampolineWithZeroAddress() {
        val gen = X86StubGenerator()
        val stub = gen.generateTrampoline(0L)
        val mem = org.kgen.reflect.NativeMemory.viewAt(stub.address(), stub.size())
        assertEquals(0L, mem.readLong(2))
        mem.close()
        stub.close()
    }

    @Test
    fun trampolineWithMaxAddress() {
        val gen = X86StubGenerator()
        val target = Long.MAX_VALUE
        val stub = gen.generateTrampoline(target)
        val mem = org.kgen.reflect.NativeMemory.viewAt(stub.address(), stub.size())
        assertEquals(target, mem.readLong(2))
        mem.close()
        stub.close()
    }
}
